apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager
  namespace: prometheus-nerd
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
spec:
  storageClassName: vmwarevspherevolume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"
